Repository pouriyajamshidi/tcping, pull requests merged in 2023-09, with the labels that each got.

#143 remove size instruction
  Makefile
Labels: cleanup

#144 Refactor/minor cleanups and v2.4.0 release
  CHANGELOG.md
  Makefile
  README.md
  db.go
  go.mod
  go.sum
  statsprinter.go
  tcping.go
Labels: enhancement, cleanup, refactor

#148 mention false positives by antimalware systems on Windows systems
  README.md
Labels: documentation

#150 reduce RTT floating point precision when storing to db
  db.go
  db_test.go
Labels: enhancement

#149 Update process user input
  tcping.go
Labels: refactor
