Repository pouriyajamshidi/tcping, pull requests merged in 2023-11, with the labels that each got.

#153 bump cosign version
  .github/workflows/container-publish.yml
Labels: chore

#154 bump GitHub Actions version
  .github/workflows/container-publish.yml
Labels: chore, CI

#155 Chore/bump code ql version
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: chore, CI

#160 Pure go sqlite
  db.go
  db_test.go
  go.mod
  go.sum
  tcping.go
Labels: enhancement, refactor
