Repository pouriyajamshidi/tcping, pull requests merged in 2023-08, with the labels that each got.

#114 refactor hostname resolution logic
  tcping.go
  tcping_test.go
Labels: enhancement, refactor

#115 fix time report bug
  tcping.go
Labels: enhancement, Bug fix

#116 Release/v2.0.0
  CHANGELOG.md
  tcping.go
Labels: release

#117 bump dependencies
  go.mod
  go.sum
Labels: chore, dependencies

#118 update Debian package name
  Makefile
Labels: enhancement, chore

#119 Chore/update readme for v2 release
  Makefile
  README.md
Labels: documentation, chore

#120 fix random IP selector bug
  tcping.go
Labels: Bug fix

#121 Chore/update gifs
  CHANGELOG.md
  Images/gifs/tcping.gif
  Images/gifs/tcping_json_pretty.gif
  Images/gifs/tcping_resolve.gif
  Images/old/tcping.gif
  Images/old/tcpingDockerDemo.gif
  Images/old/tcpingrflag.gif
  Images/old/windowsVersion.png
  Images/tapes/tcping.tape
  Images/tapes/tcping_json_pretty.tape
  Images/tapes/tcping_resolve.tape
Labels: documentation, chore

#122 improve Debian section
  README.md
Labels: documentation

#124 fixed CI warnings #98
  .github/workflows/container-publish.yml
Labels: CI

#127 Fix/convert module to v2
  CHANGELOG.md
  go.mod
Labels: chore

#129 Add option for saving to db
  .gitignore
  db.go
  db_test.go
  go.mod
  go.sum
Labels: enhancement, new feature

#130 Implement custom timeout value feature
  tcping.go
  tcping_test.go
Labels: enhancement, new feature

#132 make -db flag work
  db.go
  tcping.go
Labels: Bug fix

#133 updated Flag section in readme with `--db`
  README.md
Labels: documentation

#135 Db bug fixes
  db.go
  tcping.go
Labels: Bug fix

#136 uncomment database tests
  db_test.go
Labels: test

#137 add `-t` flag docs
  README.md
Labels: documentation

#140 update year in license file
  LICENSE
Labels: chore

#141 update flags
  README.md
Labels: documentation, cleanup
