Repository pouriyajamshidi/tcping, pull requests merged in 2023-05, with the labels that each got.

#67 add -4 and -6 flags to enforce IP address version resolution
  CHANGELOG.md
  README.md
  tcping.go
Labels: enhancement, feature request

#70 fix retry resolve logic
  CHANGELOG.md
  go.mod
  go.sum
  tcping.go
Labels: bug, enhancement

#75 docs: fix resolve gif as -r bug was fixed
  Images/gifs/tcping_resolve.gif
Labels: documentation, chore

#74 Feature: better JSON output
  .gitignore
  Images/gifs/tcping_json_pretty.gif
  Images/tapes/tcping_json_pretty.tape
  Makefile
  README.md
  go.mod
  go.sum
  statsprinter.go
  tcping.go
Labels: enhancement, new feature

#77 fix typos and broken links
  README.md
Labels: documentation, chore

#79 fix IP version enforcement bug
  tcping.go
Labels: Bug fix

#80 update for release 1.22.1
  CHANGELOG.md
  tcping.go
Labels: documentation, chore

#76 refactor: use canonical time operations instead of bare uint/float/string
  statsprinter.go
  tcping.go
  tcping_test.go
Labels: enhancement

#85 refactor: nanoToMillisecond function
  tcping.go
  tcping_test.go
Labels: enhancement

#86 update Windows Terminal link
  README.md
Labels: documentation

#87 feat: add `c` flag
  README.md
  tcping.go
Labels: new feature

#88 refactor: remove printing logic from main module and vice versa
  statsprinter.go
  statsprinter_test.go
  tcping.go
  tcping_test.go
Labels: enhancement, cleanup

#90 feat: report hostname changes
  statsprinter.go
  tcping.go
Labels: enhancement, new feature

#92 tests: add basic test server and probe success/fail tests
  statsprinter_test.go
  tcping_test.go
Labels: enhancement, test
