Repository pouriyajamshidi/tcping, pull requests merged in 2024-10, with the labels that each got.

#238 Release version 2.6.0
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  tcping.go
Labels: release

#237 Added tests TestPrintProbeSuccess and TestPrintProbeFail
  statsprinter_test.go
Labels: test

#248 docs/add chinese translation
  README.cn.md
  README.md
Labels: documentation

#245 Rewrite Makefile
  .gitignore
  Makefile
  README.md
  tcping.go
Labels: enhancement, release

#250 Correct Chinese expression in the README page : 中国人 -> 中文
  README.md
Labels: documentation

#251 Containerise build process
  .dockerignore
  .github/workflows/container-publish.yml
  Dockerfile
  Makefile
Labels: enhancement
