Repository pouriyajamshidi/tcping, pull requests merged in 2024-01, with the labels that each got.

#180 Cleanup/user flag code and comments
  Dockerfile
  LICENSE
  db.go
  db_test.go
  tcping.go
Labels: cleanup

#181 implement display failures only flag
  tcping.go
Labels: new feature

#182 release version 2.5.0
  CHANGELOG.md
Labels: release

#183 update Makefile version and tidy go modules
  Makefile
  go.mod
  go.sum
Labels: cleanup

#186 update flag section of README to include show-failures-only
  README.md
Labels: documentation

#188 Refactor Makefile: Split build section into smaller, distinct targets
  Makefile
Labels: refactor
