Repository pouriyajamshidi/tcping, pull requests merged in 2025-01, with the labels that each got.

#285 Release/version 2.7.0
  CHANGELOG.md
  Makefile
  csv.go
  csv_test.go
  db.go
  db_test.go
  go.mod
  go.sum
  statsprinter.go
  statsprinter_test.go
  tcping.go
Labels: release

#286 update flags for v2.7.0 release
  README.md
Labels: documentation

#288 rename plane to plain printer
  CHANGELOG.md
  statsprinter.go
  statsprinter_test.go
  tcping.go
Labels: refactor

#289 fix Windows builds due to lack of defined OS type
  Makefile
Labels: release

#290 Update flags in README.cn.md
  README.cn.md
Labels: documentation

#291 apply revive's suggestions
  CHANGELOG.md
  csv.go
  tcping.go
Labels: cleanup

#294 revamp and simplify README
  README.md
Labels: documentation

#295 fix directives and some links
  README.md
Labels: documentation

#296 more fixes to the README
  README.md
Labels: documentation

#298 update CHANGELOG
  CHANGELOG.md
Labels: documentation

#300 Fix/name resolution with 4 flag
  CHANGELOG.md
  tcping.go
Labels: Bug fix

#302 add WinGet instructions and minor readability improvements
  README.md
Labels: documentation

#303 add WinGet
  CHANGELOG.md
Labels: documentation

#304 update for release v2.7.1
  CHANGELOG.md
Labels: release

#309 bump version to 2.7.1
  Makefile
Labels: release
